[features]
seeds = false
[programs.localnet]
sol_dev = "Daoa93bPj45FmxkeeKA7cginUou4MKSdYha8ApHehx4j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ymc182/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
